name: vulpz-train-api
services:
  database:
    container_name: database
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: password
      POSTGRES_DB: train
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql
    networks:
      - application
  tile-server:
    container_name: tile-server
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data:ro
    command: --config /data/configuration.json
    networks:
      - application
  application:
    build:
      context: .
      dockerfile: dockerfile
    container_name: application
    restart: unless-stopped
    secrets:
      - key-private
      - key-public
      - email
      - open-router
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ENVIRONMENT=development
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=application
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=train
    depends_on:
      - database
    volumes:
      - ./documentation:/documentation:ro
    networks:
      - application
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - application
      - tile-server
    volumes:
      - ./scalar.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/api.train.conf:/etc/nginx/conf.d/api.train.conf:ro
      - ./nginx/mapping.api.train.conf:/etc/nginx/conf.d/mapping.api.train.conf:ro
      - ./nginx/documentation.api.train.conf:/etc/nginx/conf.d/documentation.api.train.conf:ro
      - ./certbot/configuration:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
    networks:
      - application
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/configuration:/etc/letsencrypt:rw
    restart: "no"

secrets:
  key-private:
    file: ./secret/base64/ed25519
  key-public:
    file: ./secret/base64/ed25519.pub
  email:
    file: ./secret/email
  open-router:
    file: ./secret/open-router

volumes:
  database:

networks:
  application:
