name: vulpz-train-api
services:
  database:
    container_name: database
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: password
      POSTGRES_DB: train
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql
  tile-server:
    container_name: tile-server
    image: maptiler/tileserver-gl
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data:ro
    command: --config /data/configuration.json
  application:
    build:
      context: .
      dockerfile: dockerfile
    container_name: application
    restart: unless-stopped
    secrets:
      - key-private
      - key-public
      - email
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - ENVIRONMENT=development
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=application
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=train
    depends_on:
      - database
    volumes:
      - ./documentation:/documentation:ro

secrets:
  key-private:
    file: ./secret/base64/ed25519
  key-public:
    file: ./secret/base64/ed25519.pub
  email:
    file: ./secret/email

volumes:
  database:
